# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170615_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='creator_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver_id',
        ),
        migrations.AddField(
            model_name='message',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creators', to='app.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receivers', to='app.User'),
            preserve_default=False,
        ),
    ]
